sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
notifications:
  on_success: never
  on_failure: always
before_install:
  - nvm install 8
install:
  - yarn
before_script:
  - yarn lerna bootstrap
script:
  - yarn test:unit
  - yarn test:integration