sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
notifications:
  on_success: never
  on_failure: always
before_install:
  - nvm install 8
install:
  - yarn
script:
  - yarn test
  - yarn intest