import { loadedConfig as config } from './config';
import { relative, eachEntity, mapEntity, getFolderName } from './utils';

export default {
  __warning_header: '/*! Generated by redux-scfld not for editing */',
  __info_header: '/*! Generated by redux-scfld */',
  config,
  eachEntity,
  mapEntity,
  relative,
  getFolderName,
  i(str) {
    return `\${${str}}`;
  },
  noExt(filename) {
    return filename.replace(/\.\w+$/, '');
  },
};
