/*! Generated by redux-scfld not for editing */
'use strict';

import {
    PROGRESS,
    SUCCESS,
    FAILURE,

    POSTS_FETCH_PAGE,

} from '../types';


import fetchPage from './posts/fetch-page.js';



function createFetchPageProgress(...args) {
    return {
        type: POSTS_FETCH_PAGE,
        phase: PROGRESS,
        args
    };
}
function createFetchPageSuccess(result) {
    return {
        type: POSTS_FETCH_PAGE,
        phase: SUCCESS,
        result
    };
}
function createFetchPageFailure(error) {
    return {
        type: POSTS_FETCH_PAGE,
        phase: FAILURE,
        error
    };
}

export const postsFetchPage = (...args) => {
    return (dispatch, getState) => {
        dispatch(createFetchPageProgress(...args));
        return Promise.resolve( fetchPage(getState, ...args) )
            .then( result => dispatch(createFetchPageSuccess(result)) )
            .catch( error => dispatch(createFetchPageFailure(error)) );
    }
};

