/*! Generated by redux-scfld not for editing */
'use strict';

import {

    POSTS_FETCH_PAGE,

} from './../types';

import defaultState from '../default-state';


import postsFetchPage from './posts/fetch-page.js';


const reducers = {

    [POSTS_FETCH_PAGE]: postsFetchPage,

};

export default function(state = defaultState, action) {
    if(action.type && (action.type in reducers)) {
        return reducers[action.type](state, action);
    }
    return state;
};