/*! Generated by redux-scfld not for editing */
'use strict';

export const PROGRESS = 'PROGRESS';
export const SUCCESS = 'SUCCESS';
export const FAILURE = 'FAILURE';


export const POSTS_FETCH_PAGE = 'POSTS_FETCH_PAGE';

