'use strict';

import {loadedConfig as config} from './config';
import {relative, eachEntity, mapEntity} from './utils';

export default {
    interpolate: /{([^\s]+)}/g,
    imports: {
        __warning_header: '/*! Generated by redux-scfld not for editing */',
        __info_header: '/*! Generated by redux-scfld */',
        config,
        eachEntity,
        mapEntity,
        relative,
        i(str) { return `\${${str}}`;}
    }
};