'use strict';

const {eachEntity} = require('./utils');

module.exports = {
    interpolate: /{([^\s]+)}/g,
    imports: {
        __warning_header: '/*! Generated by redux-scfld not for editing */',
        __info_header: '/*! Generated by redux-scfld */',
        eachEntity
    }
};